qrc!(qml_resources,
    "/" {
        "assets/logo.svg",
        "qml/Main.qml",
        "qml/components/DownloadDialog.qml",
        "qml/components/HeaderListItem.qml",
        "qml/components/Messager.qml",
        "qml/components/Player.qml",
        "qml/components/PlayerToolbar.qml",
        "qml/components/SongListItem.qml",
        "qml/components/SongDialog.qml",
        "qml/components/TabsList.qml",
        "qml/components/TransferFileDialog.qml",
        "qml/graphics/default.png",
        "qml/logic/Api.js",
        "qml/logic/CoverCache.js",
        "qml/logic/Database.js",
        "qml/ui/About.qml",
        "qml/ui/Album.qml",
        "qml/ui/Artist.qml",
        "qml/ui/Credits.qml",
        "qml/ui/Library.qml",
        "qml/ui/LibrarySongs.qml",
        "qml/ui/NewAlbums.qml",
        "qml/ui/NowPlaying.qml",
        "qml/ui/PlaylistDetail.qml",
        "qml/ui/Queue.qml",
        "qml/ui/Search.qml",
        "qml/ui/SearchHistory.qml",
        "qml/ui/SettingsPage.qml",
        "qml/ui/TopArtists.qml",
    },
);

pub fn load() {
    qml_resources();
}
